[package]
name = "repost-bot"
version = "0.5.0"
authors = ["Jonathan Webb <jonathan@webb.nyc>"]
edition = "2021"
rust-version = "1.58"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
opt-level = 3

[profile.dev]
split-debuginfo = "unpacked"

[dependencies]
chrono = "0.4"
url = "2"
linkify = "0.8.0"
regex = "1"
lazy_static = "1.4.0"
humantime = "2.1.0"
log = "0.4"
simple_logger = "2"
phf = { version = "0.10", features = ["macros"] }
unicode-segmentation = "1.7"
rand = "0.8"
paste = "1.0"
time = "0.3"
console-subscriber = "0.1.3"

[dependencies.serenity]
version = "0.10"
default-features = false
features = ["client", "gateway", "rustls_backend", "model", "cache", "http"]

[dependencies.tokio]
version = "1.17"
features = [ "rt", "time", "macros", "rt-multi-thread", "tracing"] 

[dependencies.rusqlite]
version = "0.27"
features = ["bundled", "chrono"]
