[package]
name = "repost-bot"
version = "0.2.0"
authors = ["Jonathan Webb <jonathan@webb.nyc>"]
edition = "2018"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1

[dependencies]
url = "2"
linkify = "0.7.0"
phf = { version = "0.9", features = ["macros"] }

[dependencies.serenity]
version = "0.10"
default-features = false
features = ["client", "gateway", "rustls_backend", "model", "cache", "http"]

[dependencies.tokio]
version = "1.0"
features = ["macros", "rt-multi-thread"] 

[dependencies.rusqlite]
version = "0.25.3"
features = ["bundled"]